### ISSUE TITLE
request to make commit message more understandable

### ISSUE THREAD

**Issue by vuhailongkl97** [nguyenzung/kos#10]
Hi,
I joined this project recently, I would like to learn more about OS, I really appreciate it if contributors have more attention to their **committed message or documentation** to others like me can understand what it does.

like this https://github.com/nguyenzung/kos/commit/13f361e4da99addbd16eada5a6c028c964fa6e5a
have many "magic numbers" and the hard part written in asm
Thanks.

**Comment by nguyenzung** [comment]
I agreed,

I also have a plan writing a tutorial about writing a simple OS. Maybe i will start when the OS supports multi-cores CPU, hope that i can start tutorial in next few weeks. Currently, i am quite busy, have just around an hour after lunch and 1.5 hours from 10h30 PM for this project. 

Also, if you guys have time, we can have a meeting so that i can explain what i have archived.

**Comment by vuhailongkl97** [comment]
if writing a document was scheduled, it's ok, however, could you please add more comments on changes?

**Comment by nguyenzung** [comment]
Sure
